apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service
  labels:
    app.kubernetes.io/name: test-service
    app: test-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-service
      app: test-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-service
        app: test-service
    spec:
      containers:
        - name: server
          image: node:21
          imagePullPolicy: Always
          ports:
            - name: server
              containerPort: 8080
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            requests:
              cpu: "50m"
              memory: "128M"
            limits:
              memory: "512M"
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: test-service-configuration
                  key: PORT
