apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: test-service-configuration
    behavior: create
    literals:
      - PORT=
